export const SET_USER_LOGIN_ERRORS = 'SET_USER_LOGIN_ERRORS';
export const SET_USER = 'SET_USER';
export const SET_CONNECTED_USER = 'SET_CONNECTED_USER';
export const SET_DISCONNECTED_USER = 'SET_DISCONNECTED_USER';
