export const SET_USER_LOGIN_ERRORS = 'SET_USER_LOGIN_ERRORS';
export const SET_USER = 'SET_USER';
export const SET_CONNECTED_USER = 'SET_CONNECTED_USER';
export const SET_DISCONNECTED_USER = 'SET_DISCONNECTED_USER';
export const CONNECT_NEW_USER = 'CONNECT_NEW_USER';
export const DISCONNECT_A_USER = 'DISCONNECT_A_USER';

export const FETCH_CONVERSATIONS = 'FETCH_CONVERSATIONS';
export const ADD_NEW_CONVERSATION = 'ADD_NEW_CONVERSATION';
export const FETCH_MESSAGES = 'FETCH_MESSAGES';
export const SET_MESSAGE_LOADING = 'SET_MESSAGE_LOADING';
export const SET_SELECTED_USER = 'SET_SELECTED_USER';
export const ADD_NEW_MESSAGE = 'ADD_NEW_MESSAGE';
export const REMOVE_A_MESSAGE = 'REMOVE_A_MESSAGE';
